services:
  - type: web
    name: ezzat-store
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn market_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0