# Generated by Django 6.0.3 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
