# Generated by Django 6.0.3 on 2026-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('port_said', 'Port Said'), ('suez', 'Suez'), ('luxor', 'Luxor'), ('asyut', 'Asyut'), ('ismailia', 'Ismailia'), ('minya', 'Minya'), ('qena', 'Qena'), ('faiyum', 'Fayoum'), ('zagazig', 'Zagazig'), ('tanta', 'Tanta'), ('damanhur', 'Damanhur'), ('el_mahalla_el_kubra', 'El Mahalla El Kubra'), ('banha', 'Banha'), ('aswan', 'Aswan'), ('mit_gammur', 'Mit Gammur'), ('shibin_el_kom', 'Shibin El Kom'), ('bani_suef', 'Beni Suef'), ('arish', 'Arish'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('matruh', 'Matrouh'), ('dakahlia', 'Dakahlia'), ('sharqia', 'Sharqia'), ('gharbia', 'Gharbia'), ('monufia', 'Monufia'), ('qalyubia', 'Qalyubia'), ('new_valley', 'New Valley'), ('north_sina', 'North Sinai'), ('south_sina', 'South Sinai'), ('red_sea', 'Red Sea')], max_length=100, null=True),
        ),
    ]
