# Generated by Django 6.0.3 on 2026-03-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='city_choices',
        ),
    ]
